<?php

/** @var $block Template */
/** @var $helper Data */

use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data;

$helper = $this->helper(Data::class);
?>
<div class="block block-search">
    <div class="block block-title"><strong><?= /* @escapeNotVerified */ __('Search') ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
            <div class="voicesearch_mic voicesearch-trigger voicesearch-trigger-mobile" id="voice-search-trigger-mobile"></div>
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{"formSelector":"#search_mini_form",
                            "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                            "destinationSelector":"#search_autocomplete"},
                            "voiceSearch":{}
                            }'
                           type="text"
                           name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                           value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                           class="input-text"
                           maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                </button>
                    <div class="voicesearch_mic voicesearch-trigger voice-search-trigger-desktop"  id="voice-search-trigger-desktop"></div>
                            </div>
                            </form>
                        </div>
                    </div>
